### ISSUE TITLE
set up CI building and releases for workflow

### ISSUE THREAD

**Issue by Locki-Locki** [Verisran/sem#101]
see potientally -
https://github.com/actions/starter-workflows/blob/main/ci/docker-image.yml
https://github.com/actions/starter-workflows/blob/main/ci/maven-publish.yml
and the lab notes if there is available/suitable CI to workflow to make automatic releases.

**Comment by Verisran** [comment]
Conditional deployment works appropriately in other branches
Will need to wait for completion of all other tasks to test if it works inside of master branch on push
